config/routes.rb
Rails.application.routes.draw do
   
  devise_for :users
  root 'pages#home'
  get 'about'=>'pages#about'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SaasConsultorio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%=link_to "Admin", root_path, class:"navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%=current_page?(root_path) ? "active": "" %>"><%=link_to "Home", root_path, method: :get %></li>
        <li class="<%=current_page?(about_path) ? "active": "" %>""><%=link_to "About", about_path, method: :get  %></li>
        <% if user_signed_in? %>
          <li><%=link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <%else%>
          <li class="<%=current_page?(new_user_registration_path) ? "active": "" %>""><%=link_to "Sign Up",new_user_registration_path, method: :get  %></li>
          <li class="<%=current_page?(new_user_session_path) ? "active": "" %>""><%=link_to "Log In", new_user_session_path, method: :get  %></li>
        <%end%>
        <!--<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>-->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div class="row col-md-8 col-md-offset-2">
     <p class="text-center"><strong>About</strong></p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <div class="row col-md-8 col-md-offset-2">
     <p class="text-center"> Bienvenidos al sistema de administracion de consultorios</p>
  </div>
</div>